package com.it.competition.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplyinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public ApplyinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdIsNull() {
            addCriterion("competition_id is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdIsNotNull() {
            addCriterion("competition_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdEqualTo(Integer value) {
            addCriterion("competition_id =", value, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdNotEqualTo(Integer value) {
            addCriterion("competition_id <>", value, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdGreaterThan(Integer value) {
            addCriterion("competition_id >", value, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("competition_id >=", value, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdLessThan(Integer value) {
            addCriterion("competition_id <", value, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdLessThanOrEqualTo(Integer value) {
            addCriterion("competition_id <=", value, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdIn(List<Integer> values) {
            addCriterion("competition_id in", values, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdNotIn(List<Integer> values) {
            addCriterion("competition_id not in", values, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdBetween(Integer value1, Integer value2) {
            addCriterion("competition_id between", value1, value2, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("competition_id not between", value1, value2, "competitionId");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleIsNull() {
            addCriterion("competition_title is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleIsNotNull() {
            addCriterion("competition_title is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleEqualTo(String value) {
            addCriterion("competition_title =", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleNotEqualTo(String value) {
            addCriterion("competition_title <>", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleGreaterThan(String value) {
            addCriterion("competition_title >", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleGreaterThanOrEqualTo(String value) {
            addCriterion("competition_title >=", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleLessThan(String value) {
            addCriterion("competition_title <", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleLessThanOrEqualTo(String value) {
            addCriterion("competition_title <=", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleLike(String value) {
            addCriterion("competition_title like", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleNotLike(String value) {
            addCriterion("competition_title not like", value, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleIn(List<String> values) {
            addCriterion("competition_title in", values, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleNotIn(List<String> values) {
            addCriterion("competition_title not in", values, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleBetween(String value1, String value2) {
            addCriterion("competition_title between", value1, value2, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionTitleNotBetween(String value1, String value2) {
            addCriterion("competition_title not between", value1, value2, "competitionTitle");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeIsNull() {
            addCriterion("competition_start_time is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeIsNotNull() {
            addCriterion("competition_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeEqualTo(Date value) {
            addCriterion("competition_start_time =", value, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeNotEqualTo(Date value) {
            addCriterion("competition_start_time <>", value, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeGreaterThan(Date value) {
            addCriterion("competition_start_time >", value, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("competition_start_time >=", value, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeLessThan(Date value) {
            addCriterion("competition_start_time <", value, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("competition_start_time <=", value, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeIn(List<Date> values) {
            addCriterion("competition_start_time in", values, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeNotIn(List<Date> values) {
            addCriterion("competition_start_time not in", values, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeBetween(Date value1, Date value2) {
            addCriterion("competition_start_time between", value1, value2, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("competition_start_time not between", value1, value2, "competitionStartTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeIsNull() {
            addCriterion("competition_end_time is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeIsNotNull() {
            addCriterion("competition_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeEqualTo(Date value) {
            addCriterion("competition_end_time =", value, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeNotEqualTo(Date value) {
            addCriterion("competition_end_time <>", value, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeGreaterThan(Date value) {
            addCriterion("competition_end_time >", value, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("competition_end_time >=", value, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeLessThan(Date value) {
            addCriterion("competition_end_time <", value, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("competition_end_time <=", value, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeIn(List<Date> values) {
            addCriterion("competition_end_time in", values, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeNotIn(List<Date> values) {
            addCriterion("competition_end_time not in", values, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeBetween(Date value1, Date value2) {
            addCriterion("competition_end_time between", value1, value2, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andCompetitionEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("competition_end_time not between", value1, value2, "competitionEndTime");
            return (Criteria) this;
        }

        public Criteria andStudentsNumIsNull() {
            addCriterion("students_num is null");
            return (Criteria) this;
        }

        public Criteria andStudentsNumIsNotNull() {
            addCriterion("students_num is not null");
            return (Criteria) this;
        }

        public Criteria andStudentsNumEqualTo(Integer value) {
            addCriterion("students_num =", value, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumNotEqualTo(Integer value) {
            addCriterion("students_num <>", value, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumGreaterThan(Integer value) {
            addCriterion("students_num >", value, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("students_num >=", value, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumLessThan(Integer value) {
            addCriterion("students_num <", value, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumLessThanOrEqualTo(Integer value) {
            addCriterion("students_num <=", value, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumIn(List<Integer> values) {
            addCriterion("students_num in", values, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumNotIn(List<Integer> values) {
            addCriterion("students_num not in", values, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumBetween(Integer value1, Integer value2) {
            addCriterion("students_num between", value1, value2, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentsNumNotBetween(Integer value1, Integer value2) {
            addCriterion("students_num not between", value1, value2, "studentsNum");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNumIsNull() {
            addCriterion("student_num is null");
            return (Criteria) this;
        }

        public Criteria andStudentNumIsNotNull() {
            addCriterion("student_num is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNumEqualTo(String value) {
            addCriterion("student_num =", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumNotEqualTo(String value) {
            addCriterion("student_num <>", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumGreaterThan(String value) {
            addCriterion("student_num >", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumGreaterThanOrEqualTo(String value) {
            addCriterion("student_num >=", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumLessThan(String value) {
            addCriterion("student_num <", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumLessThanOrEqualTo(String value) {
            addCriterion("student_num <=", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumLike(String value) {
            addCriterion("student_num like", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumNotLike(String value) {
            addCriterion("student_num not like", value, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumIn(List<String> values) {
            addCriterion("student_num in", values, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumNotIn(List<String> values) {
            addCriterion("student_num not in", values, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumBetween(String value1, String value2) {
            addCriterion("student_num between", value1, value2, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentNumNotBetween(String value1, String value2) {
            addCriterion("student_num not between", value1, value2, "studentNum");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeIsNull() {
            addCriterion("student_college is null");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeIsNotNull() {
            addCriterion("student_college is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeEqualTo(String value) {
            addCriterion("student_college =", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeNotEqualTo(String value) {
            addCriterion("student_college <>", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeGreaterThan(String value) {
            addCriterion("student_college >", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("student_college >=", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeLessThan(String value) {
            addCriterion("student_college <", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeLessThanOrEqualTo(String value) {
            addCriterion("student_college <=", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeLike(String value) {
            addCriterion("student_college like", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeNotLike(String value) {
            addCriterion("student_college not like", value, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeIn(List<String> values) {
            addCriterion("student_college in", values, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeNotIn(List<String> values) {
            addCriterion("student_college not in", values, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeBetween(String value1, String value2) {
            addCriterion("student_college between", value1, value2, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentCollegeNotBetween(String value1, String value2) {
            addCriterion("student_college not between", value1, value2, "studentCollege");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(String value) {
            addCriterion("student_phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(String value) {
            addCriterion("student_phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(String value) {
            addCriterion("student_phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("student_phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(String value) {
            addCriterion("student_phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(String value) {
            addCriterion("student_phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLike(String value) {
            addCriterion("student_phone like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotLike(String value) {
            addCriterion("student_phone not like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<String> values) {
            addCriterion("student_phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<String> values) {
            addCriterion("student_phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(String value1, String value2) {
            addCriterion("student_phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(String value1, String value2) {
            addCriterion("student_phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNull() {
            addCriterion("team_name is null");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNotNull() {
            addCriterion("team_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeamNameEqualTo(String value) {
            addCriterion("team_name =", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotEqualTo(String value) {
            addCriterion("team_name <>", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThan(String value) {
            addCriterion("team_name >", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThanOrEqualTo(String value) {
            addCriterion("team_name >=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThan(String value) {
            addCriterion("team_name <", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThanOrEqualTo(String value) {
            addCriterion("team_name <=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLike(String value) {
            addCriterion("team_name like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotLike(String value) {
            addCriterion("team_name not like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameIn(List<String> values) {
            addCriterion("team_name in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotIn(List<String> values) {
            addCriterion("team_name not in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameBetween(String value1, String value2) {
            addCriterion("team_name between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotBetween(String value1, String value2) {
            addCriterion("team_name not between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIsNull() {
            addCriterion("team_leader is null");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIsNotNull() {
            addCriterion("team_leader is not null");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderEqualTo(boolean value) {
            addCriterion("team_leader =", value, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderNotEqualTo(boolean value) {
            addCriterion("team_leader <>", value, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderGreaterThan(boolean value) {
            addCriterion("team_leader >", value, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderGreaterThanOrEqualTo(boolean value) {
            addCriterion("team_leader >=", value, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderLessThan(boolean value) {
            addCriterion("team_leader <", value, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderLessThanOrEqualTo(boolean value) {
            addCriterion("team_leader <=", value, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIn(List<Boolean> values) {
            addCriterion("team_leader in", values, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderNotIn(List<Boolean> values) {
            addCriterion("team_leader not in", values, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderBetween(boolean value1, boolean value2) {
            addCriterion("team_leader between", value1, value2, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderNotBetween(boolean value1, boolean value2) {
            addCriterion("team_leader not between", value1, value2, "teamLeader");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(boolean value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(boolean value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(boolean value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(boolean value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(boolean value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(boolean value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Boolean> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Boolean> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(boolean value1, boolean value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(boolean value1, boolean value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(String value) {
            addCriterion("result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(String value) {
            addCriterion("result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(String value) {
            addCriterion("result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(String value) {
            addCriterion("result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(String value) {
            addCriterion("result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(String value) {
            addCriterion("result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLike(String value) {
            addCriterion("result like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotLike(String value) {
            addCriterion("result not like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<String> values) {
            addCriterion("result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<String> values) {
            addCriterion("result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(String value1, String value2) {
            addCriterion("result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(String value1, String value2) {
            addCriterion("result not between", value1, value2, "result");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applyinfo
     *
     * @mbg.generated do_not_delete_during_merge Mon May 13 14:27:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}