package com.it.competition.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Competition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.id
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.title
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.content
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.upload_file
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private boolean uploadFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.students_num
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private Integer studentsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.start_time
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.end_time
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.organizer_id
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private Integer organizerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.organizer_name
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private String organizerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.reference_data
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private String referenceData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.state
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.result
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.send_result
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    private boolean sendResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.id
     *
     * @return the value of competition.id
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.id
     *
     * @param id the value for competition.id
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.title
     *
     * @return the value of competition.title
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.title
     *
     * @param title the value for competition.title
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.content
     *
     * @return the value of competition.content
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.content
     *
     * @param content the value for competition.content
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.upload_file
     *
     * @return the value of competition.upload_file
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public boolean isUploadFile() {
        return uploadFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.upload_file
     *
     * @param uploadFile the value for competition.upload_file
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setUploadFile(boolean uploadFile) {
        this.uploadFile = uploadFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.students_num
     *
     * @return the value of competition.students_num
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Integer getStudentsNum() {
        return studentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.students_num
     *
     * @param studentsNum the value for competition.students_num
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setStudentsNum(Integer studentsNum) {
        this.studentsNum = studentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.start_time
     *
     * @return the value of competition.start_time
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.start_time
     *
     * @param startTime the value for competition.start_time
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.end_time
     *
     * @return the value of competition.end_time
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.end_time
     *
     * @param endTime the value for competition.end_time
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.organizer_id
     *
     * @return the value of competition.organizer_id
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public Integer getOrganizerId() {
        return organizerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.organizer_id
     *
     * @param organizerId the value for competition.organizer_id
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setOrganizerId(Integer organizerId) {
        this.organizerId = organizerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.organizer_name
     *
     * @return the value of competition.organizer_name
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public String getOrganizerName() {
        return organizerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.organizer_name
     *
     * @param organizerName the value for competition.organizer_name
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setOrganizerName(String organizerName) {
        this.organizerName = organizerName == null ? null : organizerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.reference_data
     *
     * @return the value of competition.reference_data
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public String getReferenceData() {
        return referenceData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.reference_data
     *
     * @param referenceData the value for competition.reference_data
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setReferenceData(String referenceData) {
        this.referenceData = referenceData == null ? null : referenceData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.state
     *
     * @return the value of competition.state
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public boolean isState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.state
     *
     * @param state the value for competition.state
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setState(boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.result
     *
     * @return the value of competition.result
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.result
     *
     * @param result the value for competition.result
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.send_result
     *
     * @return the value of competition.send_result
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public boolean isSendResult() {
        return sendResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.send_result
     *
     * @param sendResult the value for competition.send_result
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    public void setSendResult(boolean sendResult) {
        this.sendResult = sendResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", uploadFile=").append(uploadFile);
        sb.append(", studentsNum=").append(studentsNum);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", organizerId=").append(organizerId);
        sb.append(", organizerName=").append(organizerName);
        sb.append(", referenceData=").append(referenceData);
        sb.append(", state=").append(state);
        sb.append(", result=").append(result);
        sb.append(", sendResult=").append(sendResult);
        sb.append("]");
        return sb.toString();
    }
}