package com.it.competition.domain;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.competition_id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private Integer competitionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_name
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_num
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private String studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_college
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private String studentCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_phone
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private String studentPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.competition_id
     *
     * @return the value of score.competition_id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public Integer getCompetitionId() {
        return competitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.competition_id
     *
     * @param competitionId the value for score.competition_id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setCompetitionId(Integer competitionId) {
        this.competitionId = competitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_id
     *
     * @return the value of score.student_id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_id
     *
     * @param studentId the value for score.student_id
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_name
     *
     * @return the value of score.student_name
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_name
     *
     * @param studentName the value for score.student_name
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_num
     *
     * @return the value of score.student_num
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_num
     *
     * @param studentNum the value for score.student_num
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_college
     *
     * @return the value of score.student_college
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public String getStudentCollege() {
        return studentCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_college
     *
     * @param studentCollege the value for score.student_college
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setStudentCollege(String studentCollege) {
        this.studentCollege = studentCollege == null ? null : studentCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_phone
     *
     * @return the value of score.student_phone
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_phone
     *
     * @param studentPhone the value for score.student_phone
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone == null ? null : studentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon May 13 16:29:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", competitionId=").append(competitionId);
        sb.append(", studentId=").append(studentId);
        sb.append(", studentName=").append(studentName);
        sb.append(", studentNum=").append(studentNum);
        sb.append(", studentCollege=").append(studentCollege);
        sb.append(", studentPhone=").append(studentPhone);
        sb.append(", score=").append(score);
        sb.append("]");
        return sb.toString();
    }
}