package com.it.competition.dao;

import com.it.competition.domain.Applyinfo;
import com.it.competition.domain.ApplyinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    long countByExample(ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int deleteByExample(ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int insert(Applyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int insertSelective(Applyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    List<Applyinfo> selectByExample(ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    Applyinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Applyinfo record, @Param("example") ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int updateByExample(@Param("record") Applyinfo record, @Param("example") ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int updateByPrimaryKeySelective(Applyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbg.generated Mon May 06 15:07:13 CST 2019
     */
    int updateByPrimaryKey(Applyinfo record);
}