package com.it.competition.dao;

import com.it.competition.domain.Competition;
import com.it.competition.domain.CompetitionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompetitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    long countByExample(CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int deleteByExample(CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int insert(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int insertSelective(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    List<Competition> selectByExample(CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    Competition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") Competition record, @Param("example") CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int updateByExample(@Param("record") Competition record, @Param("example") CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int updateByPrimaryKeySelective(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbg.generated Mon May 13 14:27:40 CST 2019
     */
    int updateByPrimaryKey(Competition record);
}