package com.it.competition.dao;

import com.it.competition.domain.Organizer;
import com.it.competition.domain.OrganizerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    long countByExample(OrganizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int deleteByExample(OrganizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int insert(Organizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int insertSelective(Organizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    List<Organizer> selectByExample(OrganizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    Organizer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Organizer record, @Param("example") OrganizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int updateByExample(@Param("record") Organizer record, @Param("example") OrganizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int updateByPrimaryKeySelective(Organizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizer
     *
     * @mbg.generated Fri Apr 26 18:38:50 CST 2019
     */
    int updateByPrimaryKey(Organizer record);
}